---
title: RESTHeart
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: docs/v5
  values:
    docs_version: 5
- scope:
    path: docs/v3
  values:
    docs_version: 3
- scope:
    path: docs/v4
  values:
    docs_version: 4
- scope:
    path: docs
  values:
    docs_version: 6
encoding: utf-8
email: info@softinstigate.com
description: Low code platform for building cloud-native HTTP microservices
baseurl: 
url: https://restheart.org
twitter_username: softinstigate
github_username: softinstigate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
paginate: 7
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title/"
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
domain: restheart.org
google_analytics_tracking_id: UA-49060386-2
hotjar_analytics: true
cookie_banner: true
blog:
  tags:
    url: "/blog/tags/"
    title_prefix: 'blog - tag: '
    layout: tag.html
  categories:
    url: "/blog/categories/"
    title_prefix: 'blog - category: '
    layout: category.html
asciidoc: {}
asciidoctor:
  attributes:
    - source-highlighter=rouge