# Site settings
title: RESTHeart
email: info@softinstigate.com
description: The leading REST API Server for MongoDB.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://restheart.org" # the base hostname & protocol for your site
twitter_username: softinstigate
github_username: softinstigate

# Build settings
markdown: kramdown
timezone: Europe/Rome
highlighter: rouge
paginate: 7
paginate_path: "/blog/page:num"
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!-- more -->"
plugins:
    - jekyll-paginate
    - jekyll-minifier
    - jekyll-sitemap

# Google Analytics
domain: restheart.org
google_analytics_tracking_id: UA-49060386-2

# Hotjar.com
hotjar_analytics: true

# Iubenda cookie banner
cookie_banner: true

blog:
    tags:
        url: /blog/tags/
        title_prefix: "blog - tag: "
        layout: tag.html
    categories:
        url: /blog/categories/
        title_prefix: "blog - category: "
        layout: category.html
