# Site settings
title: RESTHeart
email: andrea@softinstigate.com
description: > # this means to ignore newlines until "baseurl:"
 RESTHeart is the REST data API server for mongodb.
  Open your data, quickly build HATEOAS applications, use it as your mobile apps back-end,...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://restheart.org" # the base hostname & protocol for your site
twitter_username: ujibang
github_username:  ujibang

# Build settings
markdown: kramdown
timezone: Europe/Rome
highlighter: pygments
paginate: 7
paginate_path: "/blog/page:num"
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!-- more -->"

# Google Analytics
google_analytics_tracking_id: UA-49060386-2

blog:
    tags:
        url: /blog/tags/
        title_prefix: "blog - tag: "
        layout: tag.html
    categories:
        url: /blog/categories/
        title_prefix: "blog - category: "
        layout: category.html
