# Site settings
title: RESTHeart
email: info@softinstigate.com
description: > # this means to ignore newlines until "baseurl:"
 RESTHeart, the leading Web API for MongoDB.
 It's Fast &amp; Ligth and Production ready.
 Thought for Rapid Development: start it and the REST API is ready to use, opening data to the Web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://restheart.org" # the base hostname & protocol for your site
twitter_username: softinstigate
github_username:  softinstigate

# Build settings
markdown: kramdown
timezone: Europe/Rome
highlighter: rouge
paginate: 7
paginate_path: "/blog/page:num"
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!-- more -->"
gems: [jekyll-paginate]

# Google Analytics
google_analytics_tracking_id: UA-49060386-2

# Hotjar.com
hotjar_analytics: true

blog:
    tags:
        url: /blog/tags/
        title_prefix: "blog - tag: "
        layout: tag.html
    categories:
        url: /blog/categories/
        title_prefix: "blog - category: "
        layout: category.html
